### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by dakiesse** [parshap/node-libs-react-native#7] opened 2018-04-15 09:57 UTC
Hi,

When I try to import the stream module I see the problem: Buffer is not defined

My environment is React Native 0.55
How can I solve that?

For example, I have done like that but It didn't help me.

`import {Buffer} from 'buffer'; 
global.Buffer = Buffer; 
import stream from 'stream';`

**Comment by parshap** [comment] 2018-04-15 21:41
What error do you get? Did you follow the ["Globals"](https://github.com/parshap/node-libs-react-native#globals) section of the readme to add `require('node-libs-react-native/globals')`)?

**Comment by umpc** [comment] 2018-04-22 22:18
Hello,

I got this error after following the readme.

I fixed this issue by switching from ```import``` to ```require``` on the dependency that needed ```Buffer```.

**Comment by parshap** [comment] 2018-04-23 01:37
Mixing `import` and `require()` can have unexpected results -- `import` statements are hoisted above `require()`. People seem to run into this often (see #4), this should get noted in the readme and the examples should all use `import` instead of `require()` since that's most common in the wild.

**Comment by parshap** [comment] 2019-06-08 18:06
Closing this, because it seems to be a dupe of #4. Please reopen if still relevant.

**Closed as completed by parshap** 2019-06-08 18:06 UTC
